# Generated by Django 5.0.1 on 2024-02-15 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('uid', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=25)),
                ('password', models.CharField(max_length=25)),
            ],
            options={
                'db_table': 'Admin',
            },
        ),
        migrations.CreateModel(
            name='Drivers',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('age', models.IntegerField()),
                ('yoe', models.IntegerField()),
                ('price', models.IntegerField()),
            ],
            options={
                'db_table': 'Drivers',
            },
        ),
        migrations.CreateModel(
            name='Guides',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('age', models.IntegerField()),
                ('yoe', models.IntegerField()),
                ('price', models.IntegerField()),
            ],
            options={
                'db_table': 'Guides',
            },
        ),
        migrations.CreateModel(
            name='Places',
            fields=[
                ('pin', models.IntegerField(primary_key=True, serialize=False)),
                ('place_name', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'Places',
            },
        ),
        migrations.CreateModel(
            name='Vehicles',
            fields=[
                ('reg_no', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('ac', models.BooleanField()),
            ],
            options={
                'db_table': 'Vehicle',
            },
        ),
        migrations.CreateModel(
            name='Hotels',
            fields=[
                ('id_hotel', models.IntegerField(primary_key=True, serialize=False)),
                ('pin', models.IntegerField()),
                ('name', models.CharField(max_length=30)),
                ('place_name', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=30)),
                ('price', models.IntegerField()),
                ('fk_hot_pla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PRSV_APP.places')),
            ],
            options={
                'db_table': 'Hotels',
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('ticket_reg_no', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('from_place', models.CharField(max_length=30)),
                ('to_place', models.CharField(max_length=30)),
                ('distance', models.IntegerField()),
                ('sdate', models.DateField()),
                ('edate', models.DateField()),
                ('veh_reg_no', models.IntegerField()),
                ('dri_id', models.IntegerField()),
                ('gui_id', models.IntegerField()),
                ('fk_tic_dri', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PRSV_APP.drivers')),
                ('fk_tic_gui', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PRSV_APP.guides')),
                ('fk_tic_pla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PRSV_APP.places')),
                ('fk_tic_veh', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PRSV_APP.vehicles')),
            ],
            options={
                'db_table': 'Ticket',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_reg_no', models.CharField(max_length=5)),
                ('name', models.CharField(max_length=25)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=1)),
                ('address', models.CharField(max_length=30)),
                ('fk_customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PRSV_APP.ticket')),
            ],
            options={
                'db_table': 'Customer',
            },
        ),
    ]
