# Generated by Django 5.0.1 on 2024-02-20 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PRSV_APP', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='name',
            new_name='fname',
        ),
        migrations.AddField(
            model_name='customer',
            name='lname',
            field=models.CharField(default='', max_length=25),
            preserve_default=False,
        ),
    ]
