# Generated by Django 5.0.1 on 2024-02-23 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PRSV_APP', '0002_rename_name_customer_fname_customer_lname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='fk_customer',
        ),
        migrations.AlterField(
            model_name='customer',
            name='ticket_reg_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PRSV_APP.ticket'),
        ),
    ]
