# Generated by Django 5.0.1 on 2024-02-23 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PRSV_APP', '0003_remove_customer_fk_customer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='fk_tic_dri',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='fk_tic_gui',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='fk_tic_pla',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='fk_tic_veh',
        ),
        migrations.AlterField(
            model_name='ticket',
            name='dri_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PRSV_APP.drivers'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='gui_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PRSV_APP.guides'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='veh_reg_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PRSV_APP.vehicles'),
        ),
    ]
