# Generated by Django 5.0.1 on 2024-02-25 09:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PRSV_APP', '0004_remove_ticket_fk_tic_dri_remove_ticket_fk_tic_gui_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='hot_reg_no',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='PRSV_APP.hotels'),
            preserve_default=False,
        ),
    ]
